version: '3'
services:
  influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: influxdb:1.7.3
    volumes:
      # Mount for influxdb data directory
      - ${HOME}/influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ${HOME}/influxdb/config:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089"
    environment:
      INFLUXDB_DB: hassio      

  # telegraf:
  #   # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
  #   image: telegraf:latest
  #   volumes:
  #     # Mount for telegraf configuration
  #     - ${HOME}/telegraf/:/etc/telegraf/
  #     # Mount for Docker API access
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - influxdb
    # networks:
    # - core

  # kapacitor:
  #   # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
  #   image: kapacitor:1.5.2
  #   volumes:
  #     # Mount for kapacitor data directory
  #     - ${HOME}/kapacitor/data/:/var/lib/kapacitor
  #     # Mount for kapacitor configuration
  #     - ${HOME}/kapacitor/config/:/etc/kapacitor/
  #   ports:
  #     # The API for Kapacitor is served on port 9092
  #     - "9092:9092"

  chronograf:
    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
    image: chronograf:1.7.7
    volumes:
      # Mount for chronograf database
      - ${HOME}/chronograf/data/:/var/lib/chronograf/
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "8888:8888"
    depends_on:
      - influxdb
      # - kapacitor
      # - telegraf
